### ISSUE TITLE
How to hide a specific symbol?

### ISSUE THREAD

**Issue by JarisGV** [VincentLoy/jquery.tweetParser#14]
Hello,

I'd like to hide a specific symbol in the rendered HTML. e.g. I'd like to type ``@username`` but in the HTML I would like to have it rendered without the @ before the username. In the same way I'd like to hide https:// from the output. E.g.: ``https://mysite.com`` becomes mysite.com in HTML output.

How can I achieve it?

![Example](https://user-images.githubusercontent.com/19142770/115789786-1192ef80-a39c-11eb-994b-6b8bdbad3099.png)

**Comment by VincentLoy** [comment]
Hi @jarisgv 
currently, it's not directly possible with the lib. But it should be very easy to implement this feature as an optional one :)

**Comment by JarisGV** [comment]
🙏🙏🙏
