### ISSUE TITLE
Feature request: Eclipses on urls

### ISSUE THREAD

**Issue by cibulka** [VincentLoy/jquery.tweetParser#4]
Thanks for an awesome parser! I have a quick feature request though.

Would you consider to also include hiding long URLs behind the eclipse as Twitter does?

![screen shot 2015-06-06 at 5 01 11 pm](https://cloud.githubusercontent.com/assets/3989833/8020120/abc89d92-0c6d-11e5-9d6d-f21e523b0bd2.png)

**Comment by VincentLoy** [comment]
Hey @cibulka ! Happy that you like the plugin !

However, the implementation of this feature seems to be impossible because the plugin does not interact with the Twitter API.

**Comment by cibulka** [comment]
How is this related to Twitter api though? If I understand the eclipse behaviour correctly, it is just a text parser thing. If the parser finds URL that is "too long", it strips it from "http", cuts it to shorter length and adds 3 dots, no?

**Comment by cibulka** [comment]
And by "eclipse", I obviously mean "ellipses" (as in "three dots"). :) Sorry for the confusion!

**Comment by VincentLoy** [comment]
The twitter API truncate your tweet when it's a long RT. So you get a response like so : 
![twitterAPIRessponse](http://image.noelshack.com/fichiers/2015/23/1433712280-t1.png) 

As you can see the tweet is a String and **the URL is truncated**... But in the same object you can access to the original retweeted status that is not truncated : 

![retweeted](http://image.noelshack.com/fichiers/2015/23/1433712287-t2.png)

**and to original URL** :

![originalUrl](http://image.noelshack.com/fichiers/2015/23/1433712292-t3.png)

So I think that the solution for developpers is to play with this kind of tricks with the datas returned by the API. And it's probably what twitter is actually doing too.

**Comment by cibulka** [comment]
I see I didn't examine the incoming JSON object properly! Thanks again.
