### ISSUE TITLE
Space between text and url gets "eaten"

### ISSUE THREAD

**Issue by cibulka** [VincentLoy/jquery.tweetParser#5]
I've noticed one more thing - following tweet would turn up like this:

```
Awesome page: http://example.com
```

```
Awesome page:<a href="http://example.com"> http://example.com</a>
```

Noticed the space issue? Would you have time to look into this? Thanks again!

**Comment by VincentLoy** [comment]
Hi @cibulka ! Can you tell me wiche version of tweetParser you're using ? 
It work great for me using [v1.3.0](https://github.com/VincentLoy/jquery.tweetParser/releases/tag/v1.3.0)
![img](http://i.imgur.com/6hbEDwC.png)

it seems to do what it's expected : 

```
Awesome page: <a href="http://example.com"> http://example.com</a>
```

**Comment by cibulka** [comment]
Thanks for a very quick reaction!

And I have to correct myself - the space getting eating happens apparently only if dot preceeds the url. Correct example would be this:

`Awesome page. http://example.com` > `Awesome page.<a href="http://example.com"> http (...)`

I use 1.2.1 version.

**Comment by VincentLoy** [comment]
I made some tests with 1.3.1 and it seems that space is no longer eaten. 

Consider updating tweetParser to [v1.3.1](https://github.com/VincentLoy/jquery.tweetParser/releases/tag/v1.3.1)

**Comment by cibulka** [comment]
Yes, the update fixed it! Thank you.
